### ISSUE TITLE
Some browsers are unusably slow in large games or slow computers

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1]
Thing-browsers need to become more efficient.

Since you go directly into thingbrowsers from the main menu, they are not optional, and could be a problem for games with really huge lists of stuff

**Comment by bob-the-hamster** [comment]
I have been doing some profiling, and here is what I have learned.
The text slices do seem slower than the other slices. Text wrapping is hard work!
We might benefit from adding a SimpleTextSlice type. It could strip out all the fancy wrapping support and only support the bare minimum of rendering text.

However, even with all the strings removed from the planks, the thingbrowser isn't sped up enough to make a big difference.

The next thing I need to look at is some kind of lazy-loading that only loads the planks when they are on the screen... this would be very tricky if the planks had variable size, but since we are (usually?) working with fixed-size planks, I think it may be doable.

**Comment by bob-the-hamster** [comment]
Hmmm... I don't know how to make lazy-loading work when the thinglist is either a "Grid" or a "Layout"

If it was a plain container, and I was manually placing fixed-size planks in the style of a Grid, I could lazy-load. But I don't see a way to do it for a Layout (which is what all thingbrowsers currently seem to be using)

**Comment by bob-the-hamster** [comment]
Okay, I have a plan in progress for this.
I am going to split the thingbrowser slice collection into two versions, one for variable-size plank support, and one for lazy-loading support.

When we want variable size planks (just sprite browsers) then it will use a LayoutSlice and the current logic.

When we want lazy-loading (everywhere else) then it will use a ContainerSlice with the planks positioned according to index.

Whether or not I finish it this weekend depends on many factors, not all of which are under my control ;)

**Comment by bob-the-hamster** [comment]
Oops! Nope, nope nope!

That isn't going to work.

Yes, I can calculate the positions of fixed-size planks, but only if they are all going to be visible.
As soon as the filtering feature is being used, it is no longer possible. The filtering supports matching any text in the plank, and I can't match it without loading the planks.

Even if I just load the text only without creating the planks, I am still killing a large portion of whatever benefit would come from lazy-loading, because I would still have to get the strings from all the data records up front.

I need another approach...

**Comment by bob-the-hamster** [comment]
Hmmm.... we another approach is to re-examine why this is a problem.

1) The browse screen is too slow on old computers if the number of records gets too high (Powerstick Man textboxes on anything less than a Core i7, I'm looking at you)

2) The browse screens are no longer just optional helpers, since they are also the first thing you see when you enter most editors.

What if we do this?
* Implement a set of preference bitsets for skipping the top-level browser and going directly to the editor, just like  the olden days
* Leave the browsers enabled by default, but allow users to turn them off.

That avoids the worst of the problem by giving users with old computers and/or gigantic games a very simple manual workaround

Thoughts?

**Comment by bob-the-hamster** [comment]
For simplicity's sake, I am going to make this a single preference-- also I have decided it is better to do it per-computer rather than per-RPG file. If two people are collaborating on a single RPG file and one of them has an old slow computer, it doesn't make sense for them to have to toggle this bit on and off every time they pass the rpg file back and forth.

**Comment by bob-the-hamster** [comment]
Okay, I have implemented the preference.

It is located in ohrrpgce_config.ini and is named thingbrowser.enable_top_level
The default value is YES

There is also UI for toggling it in the "Edit general Game Settings" screen. Even though it is not game-specific, that still seemed like the simplest and clearest place to put it.

Technically this bug is still not resolved though, because I haven't given the same treatment to the "Items" menu yet, since it always worked a little differently.

**Comment by rversteegen** [comment]
Adding a config option to disable the thing browsers is a sensible workaround for now, except it doesn't work for the spriteset editor, and slow menus still need fixing.
And the map browser is also a problem. Bird and Chalkflower have both complained about the lag when a minimap for a large map is rendered on a slow computer. (There is already a config option to set how large a map has to be before rendering its minimap is delayed for a split second after it's selected in the browser.)

Anyway, there are multiple different types of slowness:
-the framerate while in the browser
-the delay when entering the browser
-the delay when entering the browser for the first time after loading the game

And there are *many* different reasons for slowness, including but not limited to:
-drawing lots of slices
-reading lots of data records
-opening and closing a file for each data record loaded (no problem on Unix, extremely slow on Windows)
-loading sprites into the cache the first time they're acc
-reading default palettes for sprites, which aren't cached
-laying out the children of a layout slice
-yes, rendering text is actually pretty slow (relevant for huge help pages)
-rendering minimaps
-scaling-down backdrops when entering the backdrop picker

It's not clear whether you were talking about framerate, or loading time. I think loading time is the main problem, but this post is about framerate.
As for lazy loading, I think that might be a solution for loading times. But is one of the most complicated solutions, and might not be needed.

Testing with an old copy of POWERXE and a release build on x86 linux and a slow 8 year old AMD CPU.

Looking at the walkabout spriteset browser (1075 walkabouts):
-Loading the first time takes ~4 seconds, subsequently takes ~1/3s
-Laying out the layout slice each tick takes 0.1ms
-I get 31fps fullscreen (1920x1080, 2x zoom) without speedcontrol
Looking at the textbox browser (9425 textboxes):
-Loading takes ~2/3s
-Laying out the layout slice takes about 1.2ms
-10 fps fullscreen
And all other browsers are very fast (>100fps)

So, the obvious problem is drawing lots of slices that don't need to be drawn, because they're off-screen. This is an easy fix: don't draw slices that are off-screen. If they are clipping, then we know they can't have visible descendants, but I'd like to also add a new Slice bool to make that assumption without needing to clip.

Results after:
Walkabout spriteset browser:
-56fps fullscreen (disappointing!)
Textbox browser:
-51fps fullscreen

**Comment by rversteegen** [comment]
OK, finally finished and committed my changes in the above comment (I had to write those detailed docs about slice drawing to figure out the correct place to put that cull test; it's a little later than I had it originally. So much for being an easy fix!)

> I'd like to also add a new Slice bool to make that assumption without needing to clip.

After I finished implementing and documenting that, I decided it wasn't needed and got rid of it again. It was incredibly redundant to Clip and anyway I'd rather err on the side of not adding new settings.

**Comment by bob-the-hamster** [comment]
I am removing release-blocker from this bug. We still want to make further improvements, but this one is currently as good as it is going to get before the fufluns release

**Comment by rversteegen** [comment]
> I am removing release-blocker from this bug. We still want to make further improvements, but this one is currently as good as it is going to get before the fufluns release

I'm actually still (ok, I mean, "started") working on this.

**Comment by rversteegen** [comment]
I'll call this fixed. Through a bunch of optimisations (there were a lot more causes of slowness than I expected), I managed speed-ups of up to x35, (and that's not even including my rewrite of the palette cache, which gives another ~30% boost to spriteset browsing, but I'll leave that until after Fufluns).

A summary of the improvements: times to enter a menu for the first time (in milliseconds on an AMD FX-6100 3.3GHz which is a 2011-era CPU):

```
Vikings
|           | Enemies    | Attacks    |
|           |  Old | New |  Old | New |
| WindowsXP | 2230 |  63 | 1194 |  92 |
| Linux     |  314 |  24 |  114 |  29 |

The Adventures of Powerstick Man
|           | Textboxes  | Walkabouts  |
|           |  Old | New |   Old | New |
| WindowsXP | 3343 | 815 | 17217 | 591 |
| Linux     |  678 | 326 |  3595 | 163 |
```
0.8 seconds to enter the textboxes menu is still a bit unpleasant, though.

`lazyclose` is mostly to thank for narrowing the gap between Windows and Linux. Here's detailed breakdown of timings (milliseconds) for entering the Textbox thingbrowser in Vikings, showing `close` vs `lazyclose`

```
|              |           | OPENFILE | Close | loadrecord |    Fill | Create | Total |
|              |           |          |  file |            | TextBox | planks |       |
|              |           |          |       |            |         |        |       |
|--------------+-----------+----------+-------+------------+---------+--------+-------|
|              | CLOSE     |      352 |   228 |        248 |      50 |     94 |  1058 |
| WindowsXP    | LAZYCLOSE |       47 |    40 |        140 |      48 |    106 |   429 |
|--------------+-----------+----------+-------+------------+---------+--------+-------|
| WindowsXP    | CLOSE     |      283 |   186 |        244 |      54 |     90 |   928 |
| nomutex      | LAZYCLOSE |       17 |    18 |        135 |      46 |    104 |   359 |
|--------------+-----------+----------+-------+------------+---------+--------+-------|
|              | CLOSE     |      257 |    80 |        130 |      46 |     85 |   628 |
| Windows10    | LAZYCLOSE |       20 |    16 |        107 |      45 |     81 |   299 |
|--------------+-----------+----------+-------+------------+---------+--------+-------|
|              | CLOSE     |       30 |     6 |         28 |      27 |     54 |   148 |
| Linux        | LAZYCLOSE |        5 |   0.4 |         29 |      27 |     54 |   116 |
```

Key:
* Close file: CLOSE or lazyclose
* loadrecord: excluding open and close time - just seeking/reading (NOTE: these timings were taken before I optimised loadrecord
* Fill Textbox: LoadTextbox except time spent in loadrecord (including the open and close)
* Create planks: build_thing_list except time spent in LoadTextBox
* Windows10 is 19.10.
* "WindowsXP nomutex" is with mutexes in filelayer.cpp commented out (they are completely unnecessary at the moment, since we don't do file I/O on multiple threads).

Note: The timing adds a lot of overhead, and I didn't try to fix the CPU frequency. That's why you see switching from `close` to `lazyclose` affecting things it shouldn't.

Note: Comparisons across OSes aren't fair: all are on AMD FX-6100 CPUs, but Win10 is running on a CPU clocked a little slower, Windows XP is running under Virtualbox (which slows down syscalls particularly), Linux times are while running under gdb. Also I used GCC 9.1 on Linux and GCC 4.5 on Windows, which I think is to blame for the 'Fill TextBox'/'Create planks' OS differences.

Not to mention the improvements to the map browser, which was another part of this bug.

**Comment by bob-the-hamster** [comment]
Those are good numbers! Impressive optimization there! :D
