### ISSUE TITLE
"Self"- and "Ally not Self"-target attacks are treated as "Ally"-target attacks out of battle.

### ISSUE THREAD

**Issue by NathanWeasel** [ohrrpgce/ohrrpgce#1105]
Characters with spells that are only supposed to be able to heal themselves can instead be used as general-purpose ally healing spells when used out of battle, probably due to overlap with the potential of such being called from items (where it makes sense to be able to choose which hero to use them on)

**Comment by rversteegen** [comment]
"Ally Not Self" is also broken. Mefisno reported that a while ago.

Out of battle, nearly all target classes are treated as being equivalent to "Ally". If we didn't, anything that targeted enemies or previous attackers wouldn't be usable. Don't see much of an alternative to that. Of course those attacks probably aren't useful anyway. But "Self" and "Ally Not Self" can be respected.

`chkOOBtag` needs to be extended. Currently, it checks only whether heroes are targettable due to being dead -- so "Ally (including dead)" and "Dead Allies" work.
