### ISSUE TITLE
Global NPC definitions

### ISSUE THREAD

**Issue by rversteegen** [ohrrpgce/ohrrpgce#1135]
Global NPCs would be an additional list of NPC definitions that could be used on any map. You frequently want to reuse NPCs across maps. Note it is already possible to copy-paste NPC definitions, including across maps, but even if you do, if the ID varies between maps it breaks scripts.

This request is at https://rpg.hamsterrepublic.com/ohrrpgce/Plan_for_global_NPC_definitions

**Comment by FnrrfYgmSchnish** [comment]
Seems like this could be a better way to do multiple versions of the same map having the same one-time-use NPCs, rather than making one version of the map complete with NPCs and then copying them over (which -- the last time I did it, anyway -- also copies the NPCs with their one-time-use tags intact.)

**Comment by rversteegen** [comment]
Just a note: one-time-use flags getting copied over when you copy an NPC definition or a whole map is intentional

**Comment by bob-the-hamster** [comment]
This is implemented current nightly builds
