### ISSUE TITLE
(Mac bug) cursor rapidly drifting

### ISSUE THREAD

**Issue by uknighted** [ohrrpgce/ohrrpgce#1170]
I haven't updated OHRRPGCE in years, and when I finally did (running mac os x 10.11.6) the selection drifted rapidly, as if someone were holding down the arrow keys.

**Comment by rversteegen** [comment]
Hi, why did you close this bug?

I have actually seen a bug like that before, although it was fixed long ago and I think it was Windows-speciic (I think there was a gfx_directx bug like this). It was basically a rounding error. It's possible it could reappear in certain circimstances, like OS and window zoom level.

**Comment by uknighted** [comment]
The reason I closed it is because it vanished like right after I posted it, so I assumed it was an issue on my end.

**Comment by rversteegen** [comment]
OK. In my experience if you see it once and then it disappears then it's real, not a 'hiccup', as much as I always want to ignore it, it just has a mysterious trigger. No reason to think it's specific to one computer. But, yeah, I'll just try to remember this report if it's reported again instead of keeping it open. Thanks.
