### ISSUE TITLE
Fix positioning of non-default Sprite sizes in battle

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#12]
A few remaining places in battle were non-standard sized sprites are mispositioned. I don't want anyone to depend on this. Most importantly centering of attack animations over a target; secondarily also attacker-target alignment for Dash In etc.

**Comment by bob-the-hamster** [comment]
The attack portion of this is fixed now. Irregular sized attacks are centered properly

**Comment by bob-the-hamster** [comment]
And I fixed Dash-In and Teleport attacks for enemies when non-standard enemy/hero sizes were in play (heroes were already okay)

**Comment by rversteegen** [comment]
Great! That's a relief.

Actually, loading the attack sprite to lookup its size shouldn't be necessary, because it turns out attack and weapon sprite slices are already loaded by  `setup_battlesprite_slice` calls near the top of `generate_atkscript` (although, that's actually probably something that should be changed...)

**Comment by bob-the-hamster** [comment]
I thought about using those, but decided it might be better not to rely on
them
