### ISSUE TITLE
Feature request: Store target attack bitset can store multiple targets

### ISSUE THREAD

**Issue by CronosZX** [ohrrpgce/ohrrpgce#1206]
As far as I'm aware the Store target bitset can only store store one target if the attack used for it has spread or optional spread targeting.
This would be extremely useful useful for attacks that change target in the middle of the chain (casting animation on caster/altering stats/etc) as those are currently limited to single target only because of this limitation with the store target bitset.

**Comment by bob-the-hamster** [comment]
Stored target should already be capable of storing multiple targets
Try this:
* Attack 1 is optional spread, and stores target
* Attack 2 is spread, and uses target class "stored target"

Because stored targets are used as a target class, attacks that make use of the stored target should usually always be "spread" so they will pick all of the stored targets.

**Comment by rversteegen** [comment]
Yes, in fact the stored targets is a mask over all heroes/enemies, and Store Target doesn't *set* the stored target, it adds all the attack's targets to the current mask. Reset Target clears the mask. Unfortunately, combining Store Target with Reset Target is broken, see bug #42.

Did you find something confusing in the documentation? Or did it not seem to work for multiple targets when you tried it?

**Comment by CronosZX** [comment]
Ah I see why it wasn't working.
Attack 2 was set to focused so it was only targeting one of the stored targets, makes sense now that I think about it although I dont remember reading about it anywhere.
