### ISSUE TITLE
Distribute to itch.io feature

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1213]
A new feature to be added to the "Distribute Game" menu.

Choosing "Distribute to itch.io" will export your game for all available platforms (except windows exe installer, itch.io recommends strongly against these)

* use the butler command-line tool (downloading it if needed)
* Spawn web browser for butler authentication (we will never touch the user's password)
* Use appropriate channel name prefixes for platform
* Allow the user to select the channel suffix such as "-stable" or "-demo" (Need to find most common practices for this on existing itch.io games)

The user is on their own for screenshots and formatting of the text of their page, butler doesn't do that.

**Comment by rversteegen** [comment]
Cool!

We should also add the OHRRPGCE as a game engine which you can select in the game metadata when adding a game on itch.io. There's a form (previously linked on SS) where you can submit engines. AFAICT, all the info you fill out on the form isn't actually used on the website for anything, except for the link to the engine's itch.io page, if it has one.

On that note, we could also add the OHRRPGCE itself to itch.io. These day most indie game engines are there. Now that would be a lot of extra work for every stable release, which is why I didn't really want to suggest it, but if you're going to be scripting itch.io uploads with butler, then the work would reduce.

**Comment by bob-the-hamster** [comment]
This feature works now. Try it out!

You can have it push to a game page that is still in "Draft" mode, if you are not ready to release yet

**Comment by rversteegen** [comment]
Wow, nice! It works!
I notice it always downloads a x86_64 linux butler executable, though.

I see that you can upload other files and they don't get overwritten. I guess you can only have one file in each "channel"? It seems that butler has more capabilities than the web interface, I don't see anything to edit channels.

BTW, I notice something odd with the download filenames. Either butler or the website is renaming the files.
Using the distribmenu I uploaded `lightingtest.zip`, `lightingtest-mac.zip`, `lightingtest-linux-x86_64.tar.gz`, but they show on the game's page named `lightning-test-windows.zip`, `lightning-test-mac.zip`, `lightingtest-linux-x86_64.tar.gz`, and they show on the
Edit Game page named  `lightning-test-{windows,mac,linux}.zip`. So it looks like it's renaming the Mac and Windows files but not the Linux one, probably because that one doesn't have a matching extension.

**Comment by bob-the-hamster** [comment]
Oops! Yes, I forgot to have it calculate the correct butler binary to download

Yes, one file per channel. I am just using "windows" "mac" and "linux" as the channels, but they are pretty free-form.

The renaming is an odd quirk, yes. Butler actually takes apart zip files, and uploads them piece by piece, only uploading the changed parts as an optimization. It does not do this for tar.bz2 files.

The butler docs claim that they take special care not to break the permissions on mac app bundles when they upload them, though I still want to do some verification to make sure this is true.

**Comment by rversteegen** [comment]
> The butler docs claim that they take special care not to break the permissions on mac app bundles when they upload them, though I still want to do some verification to make sure this is true.

But when distributing from Windows we don't actually set file permissions correctly on .app bundle contents. We exploit the fact that the Mac builtin unzip just marks all files +x if they're marked as from a Windows FS. So it's possible something does go wrong!

**Comment by rversteegen** [comment]
Should this be closed now? Was there anything else to do?

**Comment by bob-the-hamster** [comment]
I think the only reason I have not marked it closed yet was that I have not had time to test/verify the mac apps yet

**Comment by bob-the-hamster** [comment]
I tested on Mac, and yes, the permissions are correct on the mac app after butler rezips it.

Marking this issue as complete

**Comment by rversteegen** [comment]
You didn't actually, though I didn't notice either!
