### ISSUE TITLE
Downgrade Mac Euphoria version to 4.0.5

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#1256]
Mac Nightly (and release builds) should be using Euphoria 4.0.5 instead of the newer version they are currently using.

**Comment by rversteegen** [comment]
It's better that you not do this. I've been trying to work out why I had this on my todo list, but no idea so far. I know I wanted you to downgrade To 4.0.5 on the Windows build VM in order to restore support for Win98+, which you did do (for #1241). Maybe I confused Mac with Windows.

Also, there are separate 32 and 64 bit Euphoria installations on the Mac build machine, and I didn't note down which one I thought was problematic.

**Comment by bob-the-hamster** [comment]
Okay, I'll close this WONTFIX
