### ISSUE TITLE
Master palette transition issue? Or maybe I'm incompetent

### ISSUE THREAD

**Issue by Nowewin** [ohrrpgce/ohrrpgce#1272]
Somehow, this transitions from the default palette to the selected one, even though nothing is happening between the two color checks. Is this a bug? It does not look like this should work. Sorry if this turns out to be a super simple thing and I waste your time, but I genuinely don't understand it and tried a bunch of things.

```
plotscript, weathertest, begin

# Initializing the variables used to sweep through the two palettes' color values (Red, Green, Blue)

variable (colornum)
variable (fullcolorbit)

variable (pal1R)
variable (pal1G)
variable (pal1B)

variable (pal2R)
variable (pal2G)
variable (pal2B)
colornum:= 0

# Random init values just for them not to match on the first check
    
pal1R:= 99   
pal1G:= 98   
pal1B:= 97   
pal2R:= 96   
pal2G:= 95   
pal2B:= 94   

# Initializing the variables used to fade sound and start the proper ones

while (pal1R <> pal2R && pal1G <> pal2G && pal1B <> pal2B) do

(

update palette
load palette ((anyotherpalettethanthemapsdefault))

# Get RGB values for each palette color one by one using color num as the color number

fullcolorbit:= (read color (colornum))
pal1R:= (extract color (fullcolorbit, color:red))
pal1G:= (extract color (fullcolorbit, color:green))
pal1B:= (extract color (fullcolorbit, color:blue))

# In between these two there should not be any new values coming in. Nothing is happening right??

fullcolorbit:= (read color (colornum))
pal2R:= (extract color (fullcolorbit, color:red))
pal2G:= (extract color (fullcolorbit, color:green))
pal2B:= (extract color (fullcolorbit, color:blue))

# Deal with Red value comparisons first
if (pal1R < pal2R) then 
(tweak palette (1, 0, 0, colornum, colornum))
if (pal1R > pal2R) then 
(tweak palette (-1, 0, 0, colornum, colornum))

# Deal with Green value comparisons
if (pal1G < pal2G) then 
(tweak palette (0, 1, 0, colornum, colornum))
if (pal1G > pal2G) then 
(tweak palette (0, -1, 0, colornum, colornum))

# Deal with Blue value comparisons last
if (pal1B < pal2B) then 
(tweak palette (0, 0, 1, colornum, colornum))
if (pal1B < pal2B) then 
(tweak palette (0, 0, -1, colornum, colornum))

# Apply changes and repeat if not done
increment (colornum) 

)

end
```

**Comment by rversteegen** [comment]
> In between these two there should not be any new values coming in. Nothing is happening right??

Correct. So `pal1R == pal2R`, etc, after loading them both. And so the `while` loop will only run once.

> Somehow, this transitions from the default palette to the selected one 

By "selected one" I suppose you mean `anyotherpalettethanthemapsdefault`?

`update palette` will cause any modifications to the palette (including from `load palette` and `tweak palette`) to be displayed on the screen. However because you placed it before the `load palette`, it won't display the loaded palette, unless you're running the  `weathertest` script twice? I think that's probably what you're seeing. (Make sure you've read the top of the [Master Palette and Screen Fades section](http://hamsterrepublic.com/ohrrpgce/docs/plotdictionary.html#Master%20Palette%20and%20Screen%20Fades))

Also, `load palette` also changes UI colours, and that effect happens immediately, without needing an `update palette`.

The whole script is very strange, to the point that I can't see what you're actually trying to do. Are you trying to do one step of fade to a different palette, using `tweak palette`? So this script will be run repeatedly until the displayed palette matches the target palette? If so, you should put the `update palette` at the end of the script, and the `load palette` at beginning, both outside the `while`. And you should be looping `for (colornum, 0, 255)`, not using a `while` loop.

Also, the commands you're trying to use aren't compatible.

You can't use `extract color` on the return value from `read color`. It's for use with the `get color` command. `read color` return red, green or blue values directly.
Also, `tweak palette` uses R/G/B values from 0 to 63, so don't mix it with commands that use R/G/B values from 0 to 255, such as `read color`/`extract color`. I recommend avoiding it.

I could show you how to write the script, if I knew what you wanted to do.

**Comment by Nowewin** [comment]
oh my god i just typed an entire message and it got completely annihilated because the page reloaded right as i was about to send

So basically, this was a complete mess because I was hurriedly working on a massive weather system script nearing the 500 lines already and the part of the script I snipped for this post seemed to perfectly transition between 2 palettes despite looking **completely** wrong (i spent 4 hours on it before posting and it worked almost the whole way through despite so many tests and changes, which is why i made this post, unable to explain WHY as even i couldn't tell what the hell it was doing.........)

`fade screen in`. It is that simple. The screen fades in after the title screen. So it faded from the default palette to the palette I loaded near the beginning. I tested this in the first room. That's why it worked.

Sorry for wasting your time. I'm ashamed I even got stuck on this in the first place. I've been using this engine for years. Never once worried about that fade lmao 

Well, I think I'll be fine from here, now that this is out of the way. Thanks for replying and working on this engine! It's awesome! Maybe there could be a `fade palette in` function which doesn't stop gameplay in the future? By the way, the "run game" function is really cool but with no apparent way for two .rpg files to communicate, it's very limited. Being able to send variables over would make it a lot nicer, I think.

Anyway, sorry again, and thanks again too!!!

**Comment by rversteegen** [comment]
Oh, yeah, using `fade screen in` for that purpose is not obvious. And reading through the commands in the dictionary, many of them aren't well explained; it's assumed that you have a good understanding of how it all works. Palette fades and manipulations are so common and yet tricky that a HOWTO article might be in order.

> Maybe there could be a fade palette in function which doesn't stop gameplay in the future? 

Yes, that's the plan. I've already done some preliminary work on it.

> By the way, the "run game" function is really cool but with no apparent way for two .rpg files to communicate, it's very limited. Being able to send variables over would make it a lot nicer, I think.

I was going to say "Well, you can pass up to 31 additional args to `run game` which get passed on to the new game/load game script (the same way `reset game` works)", but it turns out I hadn't implement that as I'd planned. So I've just started adding that.

But even that is a pretty poor communication. Another thing you can do is set both .rpg files to use the same set of save files, which will allow using `import globals` for example. But if one game isn't variant of the other then you can't actually load a save without getting garbage.

I'm very curious how you're actually using `run game` and what sort of communication you would like to do? Do you need something like `import globals` or is passing some numbers via `run game` enough?

**Comment by Nowewin** [comment]
Ah, about the run game command... I've been working on a visual novel, actually (not exactly the main audience for the engine, haha) and I wanted the player to be able to play games on certain days. 

I could've just programmed all the minigames into the main rpg file, but it gets very messy very quickly, especially considering they're all completely different and it'd lead to a lot of different assets scattered around. So really, I just needed to pass along a couple values to keep track of the current day in the main game, and the current progression in the minigame. 

Being able to import globals would be much better for everyone in the long run, if it isn't too much trouble for you, though! I also had no idea there was a way to set multiple games to use the same save files. How do you do that?  

Oh, yeah— I noticed that the game will show the "Loading..." screen when switching to another .rpg file, just as they do when you open them up individually, which is kind of a shame since it makes the transition very obvious. Is there an option to disable that text completely somewhere in the settings? I don't remember stumbling upon it. I think I got rid of the text a while ago by just replacing it with spaces in a hex editor so it's not a big deal, though, lol. Makes it all seamless!

Thank you again for your time and effort!!! For such an old looking engine it can do a lot of crazy stuff!
