### ISSUE TITLE
Crash when changing window zoom using F9 in places which run at 32-bit colour (gfx_sdl)

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#14]
Crash when changing window zoom using F9 in places which run at 32-bit colour, such as the browser and map browser (well, the map browser part is new)

**Comment by rversteegen** [comment]
Fixed. Much trickier than expected, this was a gfx_sdl bug. gfx_sdl2 isn't affected because it doesn't even support changing the window scale yet!

The gfx_sdl code for changing window size, zoom, and other settings is an utter mess, it's not clear what the consistency requirements are or whether they're obeyed. That was the root cause. gfx_sdl2 is a little better.

**Comment by rversteegen** [comment]
Actually, there's a lot code for changing window settings in allmodex too, since whole gfx API is bad.
