### ISSUE TITLE
Uninitialised attack or enemy record getting appended

### ISSUE THREAD

**Issue by bob-the-hamster** [ohrrpgce/ohrrpgce#17]
Uninitialised attack or enemy record (0% elemental resistances) getting appended ("loadrecord: record # is off the end of" dt6/attack.bin). Can't remember whether this is fixed. Likely new in Fufluns

**Comment by bob-the-hamster** [comment]
Steps to reproduce:
* Open the enemy editor
* Create a new enemy
* Exit the enemy editor
* Exit and save changes
* Re-open the game
* Go back into the enemy editor
* The uninitialized record will appear right *after* the new one you created in the previous session

**Comment by bob-the-hamster** [comment]
Fixed!

**Comment by rversteegen** [comment]
So the root cause of this bug was the `+ 1` in the line
``recindex = gen(genMaxEnemy) + 1``
in `enemy_editor`; ditto for attacks.
And apparently that bug was actually there since r8949 (July 2017, Dwimmercraft), which added the ability to jump between different editors. However, I think it could only be triggered by pressing Insert or + in another editor to add a new enemy/attack. When in Fufluns nightlies the Attack and Enemy thingbrowsers were added, which featured the +New button, also triggering this bug and making it easier to encounter.

For the purposes of sifting through old debug log error messages, note that this caused a "loadrecord: record # is off the end of" message when you added an enemy/attack, and a "rpgfix:Adjusting record count for Enemies/Attacks lump" message when you launched Custom next time.

**Comment by rversteegen** [comment]
And note this was fixed in r11177 and r11178.
